### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Matsu-Yoi** [michaelrsweet/htmlcss#13]
I suppose that there should be how to use it in DOCUMENTATION.md, however there is not, and I do not know how to use it.

**Comment by michaelrsweet** [comment]
@Matsu-Yoi HTMLCSS is still very much a work-in-progress and not fully baked... 

The htmlcss.html file contains auto-generated reference documentation, and I just pushed an update for changes that happened since the last updates I made (just to make sure it is up-to-date) - that might be helpful if you want to play around with what is here, but expect more changes before things stabilize enough to finalize documentation and provide examples... :/
